apiVersion: v1
kind: Service
metadata:
  name: decimas-frontend
  namespace: decimas
spec:
  type: LoadBalancer
  selector:
    app: decimas-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
