apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: decimas-frontend-hpa
  namespace: decimas
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: decimas-frontend
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
